library(MASS)
library(ellipse)
library(mvtnorm)
mu=c(4,2);mu
si=matrix(c(2,1,2,1),nrow=2,ncol=2);si
x=mvrnorm(n=10000,mu,si);x
E=eigen(si);E
Li=E$values;Li
Xi=E$vectors;Xi
elps=t(t(ellipse(si,level=0.5,npoints=1000))+mu);elps
chi=qchisq(0.5,df=2);chi
c=sqrt(chi);c
factor=c*sqrt(Li);factor
plot(x[,1],x[,2])
lines(elps,col="blue")
points(mu[1],mu[2],col="blue")
segments(mu[1],mu[2],factor[1]*Xi[1,1],factor[1]*Xi[2,1]+mu[2],col="blue")
segments(mu[1],mu[2],factor[2]*Xi[1,2],factor[2]*Xi[2,2]+mu[2],col="blue")


library(ellipse)
library(MASS)
library(mvtnorm)
mu=c(0,2)
sigma=matrix(c(4,1,1,4),nrow=2,ncol=2)
x=mvrnorm(n=1000,mu,sigma);x
eigen=eigen(sigma);eigen
lambda=eigen$values;lambda
gamma=eigen$vectors;gamma
elps=t(t(ellipse(sigma,level=0.5,npoints=1000))+mu)
chi=qchisq(0.5,df=2);chi
c=sqrt(chi);c
factor=c*sqrt(lambda);factor
plot(x[,1],x[,2])
lines(elps,col="blue")
points(mu[1],mu[2],col="blue")
segments(mu[1],mu[2],factor[1]*gamma[1,1],factor[1]*gamma[2,1]+mu[2],col="blue")
segments(mu[1],mu[2],factor[2]*gamma[1,2],factor[2]*gamma[2,2]+mu[2],col="blue")
